### PR TITLE
SCIX-272 Settings and Improve Token Management

### PR DESCRIPTION
**Pull request by thostetler**
- Update babel, msw, recaptcha, add set-cookie lib
- Consolidate account api calls
- Add a notification component
- Switch to componetized ReCAPTCHA
- Add hook for applying focus to an element on mount
- Adds a useUser hook, Adds sync utility to _app
- Clean up auth-utils, consolidate requests
- rename ssrUtils -> ssr-utils, add notification
- Add PasswordTextInput component
- Adds a /api/user endpoint for getting current userData
- Add getServerSideProps export to every page
- Move most authentication management serverside
- Remove Recaptcha and Token api entries
- Updates to several components, paths, cleanup
- Fixup settings, implement missing features
- Adds token to api state before any details page
- Updates/fixes to several hooks
- Small fixes/typing updates
- Fixes to api tests
- Remove @testing-library/react-hooks lib
#major

### CODE REVIEW

**Comment by thostetler** [comment]
@shinyichen review when you can.  I'd suggest going through commits individually, since I tried to break up the changes into sections. 
Let me know if I can clarify anything
Thanks!

**Comment by shinyichen** [comment]
Strange situation when with login/logout.
1. Click logout, nothing happens, the account dropdown still shows I am logged in.
    * When I click to go to somewhere else, now it's showing I am logged out.
2. Login again, I get `Unable to login` error. ("failed-userdata-request").
    * I go to another page, it's showing I am logged in.

https://github.com/adsabs/nectar/assets/636361/ffe21b12-1609-4272-a9da-5144c231e153

**Comment by shinyichen** [comment]
Forgot password page asks me to complete the recaptcha challenge when the page loads, I have not entered the form or click submit.

**Comment by shinyichen** [comment]
Setting > Token page is getting `Unable to fetch personal API token` error for me.

**Comment by shinyichen** [comment]
Clicking on search examples do not show in search bar, but when click search the results reflect the search examples I just clicked.

https://github.com/adsabs/nectar/assets/636361/5f4784c9-e5bd-4f05-84ce-37312e8bf56f

**Comment by shinyichen** [comment]
Setting > Library link server. My institution does not reflect previously saved selection.
 

https://github.com/adsabs/nectar/assets/636361/3d14e3c5-518c-4c3a-b71e-91623b6cfcd2

**Comment by thostetler** [comment]
@shinyichen I've made some fixes and rebased to master.  Could you take a look at it quick when you get a chance.

**Comment by shinyichen** [comment]
@thostetler I am still having the same issue with login and logout. https://github.com/adsabs/nectar/pull/321#issuecomment-1696179429.

**Pull request merged**
